### ISSUE TITLE
Add a CLI tool

### ISSUE THREAD

**Issue by asfernandes** [hoperyy/sync-directory#11]
Would be great to have a CLI tool to be called from package.json.

**Comment by hoperyy** [comment]
@asfernandes Cli has just been supported： https://github.com/hoperyy/sync-directory#cli

sync-directory@2.2.8

**Comment by asfernandes** [comment]
Only with `-w` option?

I certainly need `deleteOrphaned` too.

**Comment by hoperyy** [comment]
@asfernandes sync-directory@2.2.9

https://github.com/hoperyy/sync-directory#cli

**Comment by asfernandes** [comment]
When I use `-c` or `--copy` it still display `init:hardlink`.

**Comment by hoperyy** [comment]
@asfernandes fixed at sync-directory@2.2.10

**Comment by asfernandes** [comment]
Great!
