### ISSUE TITLE
What's the point of supportSymlink?

### ISSUE THREAD

**Issue by felixhao28** [hoperyy/sync-directory#12]
I read your code and noticed hardlinks are only created when supportSymlink is set to true. So why do you require supportSymlink to be set in order to use hardlinks, when sync-directory uses type=="hardlink" by default?

**Comment by hoperyy** [comment]
@felixhao28 
![image](https://user-images.githubusercontent.com/5757051/99234565-a7e04980-282f-11eb-8a2e-6a6fa3fe2cfa.png)

**Comment by felixhao28** [comment]
My question is does `supportSymlink: false` serves the same purpose as `type: "copy"`?

|                       | type: "copy" | type: "hardlink" |
|-----------------------|--------------|------------------|
| supportSymlink: true  | copy         | symlink          |
| supportSymlink: false | copy         | copy             |

Is this table correct?

**Comment by hoperyy** [comment]
| `supportSymlink` works on folder. | type: copy | type: hardlink |
| -- | -- | -- |
| supportSymlink: true | create a new folder | symlink the same symlink folder |
| supportSymlink: false | create a new folder | create a new folder |
@felixhao28

**Comment by felixhao28** [comment]
What is the purpose of "create a new folder name `b/`"? Shouldn't it raise an error instead?

**Comment by hoperyy** [comment]
Sometimes a project need a new `b/` rather than a symlink `b/`.

`true/false` depends on what a project needs.

Maybe supportSymlink should be `true` by default.

**Comment by felixhao28** [comment]
If a project needs a new `b/` and not wants it as a symlink, then this new `b/` should be copied instead of creating an empty directory. It does not make much sense for `sync-directory` to create an empty folder and not syncing the files inside it.

**Comment by hoperyy** [comment]
In this case, `b/` is created as a new folder (not a blank folder because sub files in `a/` will be synced to `b/`), and the sub files will also be created as hardlink or copied file. For example: file `b/a.js` is hardlink of `a/a.js` when `type: hardlink`.

**Comment by felixhao28** [comment]
Ok, that makes sense. So it is like this:

Suppose we have

```
a/
    1.js
    dir/
        2.js
```

then we get

|                       | type: "copy" | type: "hardlink" |
|-----------------------|--------------|------------------|
| supportSymlink: true  | `b/1.js: copied`<br>`b/dir: copied`<br>`b/dir/2.js: copied` | `b/1.js: symlink`<br>`b/dir: symlink`<br>`b/dir/2.js: same one` |
| supportSymlink: false | `b/1.js: copied`<br>`b/dir: copied`<br>`b/dir/2.js: copied`| `b/1.js: symlink`<br>`b/dir: new directory`<br>`b/dir/2.js: symlink` |

**Comment by hoperyy** [comment]
![image](https://user-images.githubusercontent.com/5757051/99355728-c7d14500-28e3-11eb-97c6-cd0b09634497.png)

**Comment by felixhao28** [comment]
Generally speaking, symbolic links work on folders too. It is just that this package chooses to use hardlinks instead.
