### ISSUE TITLE
Only -h option shows and -w doesn't work.

### ISSUE THREAD

**Issue by Industrial** [hoperyy/sync-directory#14]
Hello.

Using sync-directory v2.2.10 when I run `syncdir -h` the only option listed is `-h`.

Running with `-w` immediately ends the process and nothing happens.

**Comment by hoperyy** [comment]
@Industrial Fixed at sync-directory@2.2.11

**Comment by hoperyy** [comment]
@Industrial Fixed at sync-directory@2.2.12

**Comment by Industrial** [comment]
great, thanks!
