### ISSUE TITLE
Add a quiet flag to CLI

### ISSUE THREAD

**Issue by Joebayld** [hoperyy/sync-directory#15]
Can there be a flag added to the CLI to suppress all the logs? Something like `--quiet`. 

Or maybe something that indicates a sync happened but not list every file that changed when in watch mode. My CLI is full of logs because I'm changing many files at a time.

**Comment by hoperyy** [comment]
Just supported at sync-directory@2.2.16 @Joebayld

**Comment by Joebayld** [comment]
Wow that was fast. Thanks!!! Love the library.

**Comment by hoperyy** [comment]
If you like, star one maybe more helpful for it ☺
