### ISSUE TITLE
Unable to use in Oracle JET framework

### ISSUE THREAD

**Issue by rthangam** [hoperyy/sync-directory#16]
When i try to use this npm module in OJET (Oracle jet) framework i get the following issue:

When i try to use load the module using the below syntax:

**const syncjs = require('sync-directory');**

Could not find a declaration file for module 'sync-directory'. '/xxxxx/node_modules/sync-directory/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sync-directory` if it exists or add a new declaration (.d.ts) file containing `declare module 'sync-directory';`ts(7016)

What is the issue here ?

**Comment by hoperyy** [comment]
It needs a `d.ts` file. I'll add it soon @rthangam

**Comment by rthangam** [comment]
Thanks a lot

**Comment by hoperyy** [comment]
index.d.ts was added at sync-directory@2.2.19 

Pls try it.

If problems occurs, let me know, thanks! @rthangam

**Comment by rthangam** [comment]
Thanks a lot i will check
