### ISSUE TITLE
Feature Request: Ability for "initialCopy" to be passed to afterSync

### ISSUE THREAD

**Issue by Zamiell** [hoperyy/sync-directory#19]
Greetings and thanks for the library.

I'm using the afterSync callback and it works great.

However, at the beginning of execution, `sync-directory` copies over the entire directory fresh, and this spams my afterSync callback. I only want to do stuff in my afterSync callback *after* sync-directory has started its monitoring process.

How about a third argument is sent to the afterSync callback called "initialCopy" that is a boolean letting it know whether or not this particular file copy happened during initialization?

**Comment by hoperyy** [comment]
```js
require('sync-directory')(srcDir, targetDir, {
        afterSync({ type, relativePath }) {
            // type: init:hardlink / init:copy / add / change / unlink / unlinkDir
            // relativePath: relative file path
        }
});
```

Thanks for your suggestion!

The types at comments were supported long time ago but readme missed that...

`init:` is the prefix tag for initial copies.

Now readme has wrote it out.

**Comment by Zamiell** [comment]
ok, thanks
