### ISSUE TITLE
Feature Request: Ability to pass options to chokidar

### ISSUE THREAD

**Issue by Zamiell** [hoperyy/sync-directory#20]
`sync-directory` doesn't work out of the box for most use cases because it doesn't specify the awaitWriteFinish option, leading to incorrectly copied files.

I recommend setting this to true, but furthermore, allowing the end-user to specify their own chokidar options.

**Comment by hoperyy** [comment]
Good Idea!

`chokidarWatchOptions` has been added at sync-directory@2.2.21.

**Comment by hoperyy** [comment]
Good Idea!

`chokidarWatchOptions` has been added at sync-directory@2.2.21.

**Comment by Zamiell** [comment]
thanks!

also, it looks like you left a bunch of console.logs in the code, can you remove those?

**Comment by hoperyy** [comment]
done at sync-directory@2.2.22.

**Comment by Zamiell** [comment]
thanks ><
