### ISSUE TITLE
Reason for syncLocalFiles?

### ISSUE THREAD

**Issue by Venryx** [hoperyy/sync-directory#22]
What is the reason for having a separate call-path for `syncLocalFiles` at startup?

Isn't is sufficient to just use `watchLocalFiles`, with chokidar's `ignoreInitial` setting to `false`? (which is the default, and appears to be unchanged in `sync-directory`)

(There is probably a reason you wrote it this why, but I'd like to understand.)

**Comment by Venryx** [comment]
Also, a derivation of this repo called [sync-folders](https://github.com/pk-nb/sync-folders) says there is potentially a flaw/inconsistency in the include/exclude rules of `sync-directory`. I've asked the author for details on what he means.

**Comment by hoperyy** [comment]
Good questions and sorry for slow response...

I'm thinking of it and will give the answer later. @Venryx

**Comment by hoperyy** [comment]
`options.skipInitialSync: boolean` controls whether a sync is performed by default, and its default value is `false`.
