### ISSUE TITLE
[FR] Async afterSync

### ISSUE THREAD

**Issue by rayfoss** [hoperyy/sync-directory#25]
I'm currently needing to slow down sync due to quota issues. 

This would be exceedingly easy with an async hook that was awaited for.

`await new Promise(p => setTimeout(p, 50));`

Instead, I have to use this os specific, blocking, Node.js dependent, Deno breaking, incompatible, kowai abomination:

```js
  afterSync(event) {
    if (event.type === 'init:copy') { // max 50 files every 2 seconds
      process.stdout.write('.')
      execSync('sleep 0.05') // 0.04 = 50 files, 0.05 = 40 files
    }
  }
```

## Proposal

Make a new branch with everything promisified. Then release it as a new major or minor version.

**Comment by hoperyy** [comment]
Supported at `sync-directory@3.0.0` @rayfoss 

```js
const syncDirectory = require('sync-directory');

const delay = (time = 2000) => new Promise(r => setTimeout(r, time))

console.log('start'); // time a

// wait several 2s: 2 * file number
syncDirectory.async(srcDir, targetDir, {
    async afterEachSync({ type, relativePath, absolutePath }) {
        console.log(type, relativePath, absolutePath);
        await delay(2000); // delay 2s after one file was synced
    },
});

console.log('end'); // time a + 2 * (file number)
```
