### ISSUE TITLE
[Bug] Cli does not copy files after 2.2.23 -> 3.0.3

### ISSUE THREAD

**Issue by belgattitude** [hoperyy/sync-directory#26]
Congrats for the new release :medal_sports: 

Just updated to 3.0.3, and the command I use suddently stopped working.

```
yarn syncdir ../../static/assets ./public/shared-assets --copy

sync-directory cli: syncdir <from> <to> [options]
   - from:  /home/sebastien/github/nextjs-monorepo-example/static/assets
   - to:    /home/sebastien/github/nextjs-monorepo-example/apps/web-app/public/shared-assets
   - watch: false
   - deleteOrphaned: false
   - type:  copy
   - supportSymlink:  false

// Then nothing
```

On 2.2.23, 

```
yarn syncdir ../../static/assets ./public/shared-assets --copy

sync-directory cli: syncdir <from> <to> [options]
   - from:  /home/sebastien/github/nextjs-monorepo-example/static/assets
   - to:    /home/sebastien/github/nextjs-monorepo-example/apps/web-app/public/shared-assets
   - watch: false
   - deleteOrphaned: false
   - type:  copy
   - supportSymlink:  false

// here the files
init:copy:  /images
init:copy:  /images/nextjs-logo.png
init:copy:  /images/undraw
init:copy:  /images/water
init:copy:  /images/undraw/undraw_outdoor_adventure.svg
init:copy:  /images/undraw/undraw_street_food.svg
```

Was there a change in the cli options ? or maybe a bug ?

**Comment by hoperyy** [comment]
Thanks for your using. Just forgot updating cli codes....

fixed at `sync-directory@3.0.5`

![image](https://user-images.githubusercontent.com/5757051/137569983-182d6338-d040-45fd-a6fb-0ab57b3c97f4.png)

@belgattitude @rayfoss

**Comment by belgattitude** [comment]
Thanks a lot for fix, I'll confirm during the week when I'll update.

Enjoy the weekend.

**Comment by rayfoss** [comment]
@belgattitude what environment were you using? bash/zsh/WSL/git-sh/termux/BSD?

I'm thinking about how to add a peer dependency on desync and remove a TON of duplicate code while adding support for preserving metadata and faster/more efficient syncing. Making the CLI use the async code is hazardous without knowing what exactly went wrong.

My best theories right now are:
- A weird runtime environment
- Scripting in a shell without multi process support enabled, ie bash's `set -m`
