### ISSUE TITLE
Synced files are not hardlinks when watching directory on Windows

### ISSUE THREAD

**Issue by jessehallinen** [hoperyy/sync-directory#30]
I'm using the code below to watch a directory. It copies new files into target directory but those files won't be hardlinks for some reason. Is it a feature or a bug? 

Tested on Win 10 pro and Windows server 2019 datacenter.

```
const watcher = require('sync-directory')(
    "C:/Users/jesse/Desktop/source",
    "C:/Users/jesse/Desktop/target",
    {
        watch: true
    }
);
```

EDIT: If there are old files in the source folder and I restart my code then it syncs those files and they will be hardlinks. So it fails only when using watcher to detect new files.

**Comment by hoperyy** [comment]
Well It's a feature. Some other tools like webpack-dev-server will watch target folder file changes.

The file watcher won't work If the target file is always hardlink.

So the changed files will be "copied" to target folder rather than remain to be "hardlink".

**Comment by jessehallinen** [comment]
Ok thanks, then this case is closed.

**Comment by hoperyy** [comment]
Aoid copy when file changes can be supported if it's need. 

Should I support it ?

**Comment by jessehallinen** [comment]
Well, if it allows target folder files be hardlinks when using watcher then it would be useful, at least for me.

**Comment by hoperyy** [comment]
The latest version had already supported this feature by setting config `stayHardlink: true`
@jessehallinen
