### ISSUE TITLE
How I would run one-off sync?

### ISSUE THREAD

**Issue by lvfxbr** [hoperyy/sync-directory#31]
I was struggling trying to run sync only once per interval I set. Consider the following example:

```js
const syncDirectory = require("sync-directory");

const duration = 60 * 1000; // run sync each 1 minute

...

function doSync() {
    syncDirectory.sync(inputDir, outputDir, {
        deleteOrphaned: true,
        exclude: [".git", "node_modules"],
        chokidarWatchOptions: {
            persistent: false,
        },
        type: "copy",
        watch: false,
    });
}

doSync();

setInterval(() => {
    doSync();
}, duration);

```

I expect to sync my folder each 1 minute or whatever interval I set. But the command is syncing in realtime each time I change my files, it keeps persistent sync even passing the parameter to false. What should I do?

**Comment by hoperyy** [comment]
@lvfxbr  I just copied your code and run it myself.

But the case which `sync-directory` will be always watching does not happened on my side. 

Yet I found another bug: If target file exists before `sync-directory` start, it won't be changed after syncing. `sync-directory@4.0.13` has fixed it.

You can try again.  If anything wrong, please let me know, I will fixe it 😁

**Comment by lvfxbr** [comment]
@hoperyy. I found the bug making a test repository for this (version 4.0.12), like you described. Glad that you found it.

I have questions about the options I used in this example:

chokidarWatchOptions > persistent:false is it really necessary in this case?
type set to copy, as I tested, looks like if I don't set this option, it keeps syncing in realtime, can you confirm that?
PS.: I assembled the examples in this repository, it have both versions, the bug one and the new one:

https://github.com/lvfxbr/lab/commits/sync-directory-1

**Comment by hoperyy** [comment]
@lvfxbr For quetions 2

If `type` was not configed, `hardlink` will be used by default. So the src file and target file is the same file.

![image](https://user-images.githubusercontent.com/5757051/164140116-eef95d51-7423-455c-a3ca-4e69790fe9e2.png)

**Comment by hoperyy** [comment]
@lvfxbr For question 1

https://github.com/hoperyy/sync-directory/blob/master/lib/local-watch.js#L65

![image](https://user-images.githubusercontent.com/5757051/164141204-f9c44fdd-cd50-46f8-924e-740d857e7780.png)

**Comment by hoperyy** [comment]
Good! Maybe `type: 'copy'` by default will be better. Thinking of it

**Comment by hoperyy** [comment]
@lvfxbr `sync-directory@4.1.0` has set `"type": "copy"` as default.
