### ISSUE TITLE
ReferenceError: onError is not defined

### ISSUE THREAD

**Issue by globdug** [hoperyy/sync-directory#32]
Hello,
I was trying to use sync-directory and I used a relative path instead of absolute and I got an unexpected error:

```
ReferenceError: onError is not defined
    at formatParams (D:\www\bp3\node_modules\sync-directory\index.js:34:9)
    at Function.synced [as sync] (D:\www\bp3\node_modules\sync-directory\index.js:42:20)
    ...
```

In index.js at line #34 the code is:
```javascript
onError({ message: '[sync-directory] "srcDir/targetDir" must be absolute path.' });
```

But I think it should be?
```javascript
options.onError({ message: '[sync-directory] "srcDir/targetDir" must be absolute path.' });
```

I'm not expert, so I hope I didn't say a nonsense thing... 😅

**Comment by hoperyy** [comment]
@globdug 
Well done!

It's really a bug. `sync-directory@5.0.4` has been just fixed and published!

Thanks for your issue 😁l

**Comment by globdug** [comment]
You're welcome, first bug fixed of my life! 🍻
