### ISSUE TITLE
Upgraded from 5.0.8 to 5.1.3 all directories are empty 

### ISSUE THREAD

**Issue by tim-field** [hoperyy/sync-directory#50]
running as so `syncdir ../../common/src src/common --deleteOrphaned`  

This now copies with all directories empty, it broke somewhere between 5.0.8 to 5.1.3

**Comment by Zamiell** [comment]
I think the issue is that recursive directories are no longer copied. Surface level files still seem to be synced.

I'd recommend staying on version 5.0.8 for now.

hoperyy, I'd recommend adding some jest tests that test for regressions like this.

**Comment by hoperyy** [comment]
@tim-field @Zamiell  I'll check it today and fix it!

**Comment by hoperyy** [comment]
@tim-field 
@Zamiell  
sync-directory@5.1.4 has fixed it !

It's a cli only bug when adding feature `-nd, --nodeep` for better performance.

When `syncdir ../../common/src src/common --nodeep`, only first level folders and files are copied to the target folder.

**Comment by Zamiell** [comment]
its still not fixed, 5.1.5 has the same problem that doesn't recursively sync directories

**Comment by hoperyy** [comment]
I'v tried `npm i sync-directory@5.1.5 -g` and then `syncdir test/srcDir test/targetDir`

`test/srcDir` files:

![image](https://user-images.githubusercontent.com/5757051/174705615-9f2b2438-036e-4058-abc5-da11d4642655.png)

Then `test/targetDir`
![image](https://user-images.githubusercontent.com/5757051/174705708-2754de8e-a2d1-43ad-a75f-fb1162c01cda.png)

With log:

```
init:copy:  /c
init:copy:  /dir1
init:copy:  /hh
init:copy:  /c/d
init:copy:  /c/hhh
init:copy:  /dir1/a
init:copy:  /dir1/b
init:copy:  /c/hhh/aaa
```

**Comment by Zamiell** [comment]
https://github.com/Zamiell/sync-directory-bug
