### ISSUE TITLE
Support paths the same with in CLI and code

### ISSUE THREAD

**Issue by kylecordes** [hoperyy/sync-directory#51]
Currently, the CLI accepts relative paths, but the API requires absolute path.

This seems like an unnecessary difference, and a place for bugs to hide.

Thus a feature request: move whatever code cares about the difference out of the CLI code into the core code. Thus the CLI will pass paths through without caring about them, and the full functionality will be available from the API.

**Comment by hoperyy** [comment]
It's really necessary and I'll support this feature soon @kylecordes

**Comment by hoperyy** [comment]
`sync-directory@5.1.8` has supported the same params formatter between cli and api.

Differences: https://github.com/hoperyy/sync-directory/commit/25b34def4fd5be55967b191ce4b09a9bd19e0d04

@kylecordes

**Comment by kylecordes** [comment]
Thank you!
