### ISSUE TITLE
does not work with ESM

### ISSUE THREAD

**Issue by Zamiell** [hoperyy/sync-directory#54]
Is there a way to use this package from an ESM project?

**Comment by hoperyy** [comment]
"module" should be added at "package.json".

I'll add it later recently.
@Zamiell

**Comment by Zamiell** [comment]
Thank you!

**Comment by hoperyy** [comment]
`sync-directory@6.0.1` adds a new entry type `"module"` here

<img width="817" alt="image" src="https://user-images.githubusercontent.com/5757051/220957726-b5cf293d-8f15-4702-90cb-09e64b2cade9.png">

You can try to import it like this:

```
import { sync, async } from 'sync-directory'
```

You can keep telling me if it has bugs.

**Comment by Zamiell** [comment]
Thanks.

I tried it out, and it doesn't work:

![image](https://user-images.githubusercontent.com/5511220/220964256-c15480b5-b67d-4b2c-8c8c-9cd3ce64d9d6.png)

Furthermore, making end-users use this special syntax is really weird. I do not think end-users should not have to change their import style when upgrading.
In my libraries, I [publish CJS/ESM like this](https://antfu.me/posts/publish-esm-and-cjs), and its invisible to the end-users. Is it possible to do something like that here?

**Comment by hoperyy** [comment]
Well there's 2 problems here:

1. I've tested this way and it worked

```ts
import syncDirectory, { sync, async } from  'sync-directory/index.mjs';

console.log(sync) // works
```

You can try it again after `yarn add sync-directory@latest`.

2. Perhaps Node.js 14.16.1 does not support `import` without specific `mjs` file path.

I'll read some docs to skip it.

**Comment by Zamiell** [comment]
node 14 end of life is in 2 months, we may as well not support it, right?

**Comment by hoperyy** [comment]
I want to support it anyway 😁

**Comment by Zamiell** [comment]
@hoperyy node 14 is end of life now, can you make this dep work properly with ESM + normal import syntax?
