### ISSUE TITLE
index.d.ts (TypeScript typings) is out of date

### ISSUE THREAD

**Issue by grant-dennison** [hoperyy/sync-directory#57]
The TypeScript types for this package only include the default export of the synchronous sync function and have not been updated to include newer stuff like the named `async` export. This makes the new APIs difficult to use in TypeScript projects.

**Comment by hoperyy** [comment]
`sync-directory@6.0.3` has updated `index.d.ts`.
You may try it.
If there's any bugs, please let me know ☺.

**Comment by grant-dennison** [comment]
Awesome, thank you!
