### ISSUE TITLE
when copying newly added files, misses first character in file name 

### ISSUE THREAD

**Issue by antsav** [hoperyy/sync-directory#8]

**Comment by hoperyy** [comment]
I've tried myself, but it works fine. 

Can you paste some images when it works wrong ?

**Comment by antsav** [comment]
@hoperyy here is the simplest example
it shows in afterSync the correct file name though, but writes the one with first missing character

<img width="968" alt="Screen Shot 2020-06-23 at 7 04 23 AM" src="https://user-images.githubusercontent.com/1043531/85413599-dcb9d000-b51f-11ea-8404-43c52340aa02.png">

**Comment by hoperyy** [comment]
I've found the problem. 

`srcDir/targetDir` should be **absolue path**.

Version `2.2.5` was published and it will show warnings when `srcDir/targetDir` is not absolute path.

![image](https://user-images.githubusercontent.com/5757051/85507630-4079f100-b625-11ea-8bdf-0112abdfb1ad.png)

**Comment by antsav** [comment]
it works now
thanx!
